# Generated by Django 2.2 on 2019-04-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedStrings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_string', models.CharField(max_length=250)),
                ('translated_string', models.CharField(max_length=250)),
                ('language_code', models.CharField(max_length=3)),
            ],
        ),
    ]
