# Generated by Django 2.2 on 2019-04-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_translatedstrings'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechtext',
            name='language_code',
            field=models.CharField(default='en', max_length=3),
        ),
        migrations.AlterField(
            model_name='translatedstrings',
            name='language_code',
            field=models.CharField(default='en', max_length=3),
        ),
    ]
