# Generated by Django 2.2 on 2019-04-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_languagecodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechtext',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='translatedstrings',
            name='original_string',
            field=models.CharField(max_length=1000),
        ),
    ]
